asset/urls.py
from django.urls import path
from . import views

app_name    = "asset"
urlpatterns = [
    path('', views.index, name="index"),
    path('delete/<int:pk>/', views.delete, name="delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("asset.urls")),
    path('accounts/', include('allauth.urls')),
]

asset/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        db_table = "category"

    name = models.CharField(verbose_name="カテゴリ名",max_length=100)
    dt =models.DateTimeField(verbose_name="追加日", default=timezone.now)
    income = models.BooleanField(verbose_name="収支(True=収入,False=支出)", default=False)

    def __str__(self):
        return self.name

class Balance(models.Model):

    class Meta:
        db_table = "balance"

    category = models.ForeignKey(Category,verbose_name="カテゴリ",on_delete=models.CASCADE,blank=True, null=True)


    title = models.CharField(verbose_name="タイトル", max_length=100, default="")
    comment = models.CharField(verbose_name="コメント", blank=True, max_length=2000)
    income = models.IntegerField(verbose_name="収入", default=0)
    spending = models.IntegerField(verbose_name="支出", default=0)
    dt = models.DateTimeField(verbose_name="投稿日", default=timezone.now)
    pay_dt  =  models.DateTimeField(verbose_name="決済日")

    def __str__(self):
        return self.comment

asset/forms.py
from django import forms
from .models import Balance

class BalanceForm(forms.ModelForm):
    class Meta:
        model     = Balance
        fields   = [ "category","comment","income","spending","pay_dt"]


class YearForm(forms.Form):
    year     = forms.IntegerField()

asset/views.py
from django.shortcuts import render, redirect
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Balance, Category
from .forms import BalanceForm, YearForm

from django.db.models import Q
from django.http.response import JsonResponse
from django.template.loader import render_to_string

import datetime



#カテゴリ名の付与、小計値の計算(GETの他にPOSTでも使用するので関数化した)
def calc_category_sum(balances):

    balances    = list(balances.values())
    total       = 0

    for balance in balances:

        total               = total + int(balance["income"]) - int(balance["spending"])
        balance["total"]    = total

        # カテゴリ名を設定
        if balance["category_id"]:
            category            = Category.objects.filter(id=balance["category_id"]).first()
            balance["category"] = category.name

    return balances

class BalanceView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):

        categories  = Category.objects.all()

        # 最古から最新の年リストを生成(決済日)
        dt          = datetime.datetime.now()
        now_year    = dt.year  # ←最新の決算日の年を当てるべきでは？
        years       = []

        balance     = Balance.objects.order_by("pay_dt").first()

        # 最古のデータがあれば最古のデータの年から今年までのリストを作る。(これがテンプレートのselectタグになる。)
        # なければ今年だけ表示
        if balance:
            old_year = balance.pay_dt.year
            print(old_year)
            for i in range(now_year, old_year - 1, -1):
                years.append(i)
        else:
            years.append(now_year)

        # yearの指定があれば、年のデータを抜き取り検索する。指定がなければ現在の年を指定
        form = YearForm(request.GET)
        selected_year = now_year

        if form.is_valid():
            data = form.cleaned_data
            selected_year = data["year"]

        # 1年分のデータ
        balances = Balance.objects.filter(pay_dt__year=selected_year).order_by("pay_dt")

        # 月ごとのデータ
        months = []
        for i in range(1, 13):
            months.append(Balance.objects.filter(pay_dt__year=selected_year, pay_dt__month=i).order_by("pay_dt"))


        # 小計値の計算(1年分)
        balances    = calc_category_sum(balances)

        # 小計値の計算(月ごと)
        month_list  = []
        for month in months:
            month_list.append( calc_category_sum(month) )



        context = {"balances": balances,
                   "categories": categories,
                   "years": years,
                   "months": month_list,
                   "selected_year": selected_year,
                   }

        return render(request, "asset/index.html", context)

    def post(self, request, *args, **kwargs):


        json    = {"error":True} 
        form    = BalanceForm(request.POST)

        if not form.is_valid():
            print("バリデーションNG")
            return JsonResponse(json)

        print("バリデーションOK")
        result  = form.save()

        #ここまでで受け取ったデータを保存している。



        #投稿があった月と年を抜き取り
        selected_month  = result.pay_dt.month
        selected_year   = result.pay_dt.year

        #Ajax送信と同時に選択中の年を同時に送信、受け取り後、以下のバリデーションと抽出を行う。
        #複雑になりすぎるので後日実装
        """
        year_form       = YearForm(request.POST)
        if year_form.is_valid():
            data            = year_form.cleaned_data

            #選択中の年と投稿された年が不一致の場合、レンダリングはせずにそのままレスポンスを返す。
            if data["year"] != selected_year:
                return JsonResponse(json)
        """


        year    = Balance.objects.filter(pay_dt__year=selected_year).order_by("pay_dt")
        month   = Balance.objects.filter(pay_dt__year=selected_year, pay_dt__month=selected_month).order_by("pay_dt")
        
        year    = calc_category_sum(year)
        month   = calc_category_sum(month)


        #yearとmonthのレンダリング結果を文字列でそれぞれ返す。
        context = { "balances":year }
        year    = render_to_string('asset/table.html', context ,request)
        context = { "balances":month }
        month   = render_to_string('asset/table.html', context ,request)

        #jsonに追加。文字列のレンダリング結果をJavaScriptが指定した箇所に張り付けする。
        json["error"]           = False
        json["year"]            = year
        json["month"]           = month
        json["selected_month"]  = selected_month



        #Ajaxを送信した後はjsonを返却する(JsonResponse)
        return JsonResponse(json)


index = BalanceView.as_view()


class BalanceDeleteView(LoginRequiredMixin, View):

    def post(self, request, pk, *args, **kwargs):
        balance = Balance.objects.filter(id=pk).first()
        balance.delete()

        return redirect("asset:index")


delete = BalanceDeleteView.as_view()

templates/asset/index.html
{% load static %}

<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--Jqueryを追加-->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.4.0/chart.js" integrity="sha512-+POM1aKUkb5l91zDBDtxn0dlY5wazuQFtCXin/47Z+eE7AnMuFBMrNjkZA1P6m+infsMMSthlsPNh1rjBtAPBA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!--日本語化用JS-->
    <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

    <!--Ajax送信時にCSRFトークンをセットした上で送信する。-->
    <script src="{% static 'common/js/ajax.js' %}"></script>

    <!-- cssは一部が不具合を起こしているようなので、全て書き換え-->
    <link rel="stylesheet" href="{% static 'asset/css/style.css' %}">
    <script src="{% static 'asset/js/script.js' %}"></script>

    <!--fontawesomeは
        https://fontawesome.com/download#pro-packages
        からFreeforWeb(CSSやJSが含まれている方)をDLして
        css(fontawesomeに改名)とwebfontをcommon/css/に配置
    -->

    <link rel="stylesheet" href="{% static 'common/css/fontawesome/all.min.css' %}">

    <style>
        body{
            background-image: url("{% static 'asset/img/ookamikun1.png' %}");
            background-attachment: fixed;
            background-size: cover;
            background-position: right 10% bottom 10%;
            }
    </style>
</head>
<body>

    <header>
        <input id="l_sidebar" class="l_sidebar_button" type="checkbox">
        <div class="left_header">
        <label class="l_sidebar_label" for="l_sidebar">
                <i class="fas fa-bars"></i>
                <i class="fas fa-times"></i>
            </label>
            <a class="header_link" href="{% url 'asset:index' %}"><h1>メニュー</h1></a>
            <div class="header_right_content">
                <!--TODO:ここにログインのアイコンなどを-->
            </div>
        </div>
        <div class="l_sidebar_menu">

            <a href="{% url 'account_logout' %}">ログアウト</a>

        </div>
        <label class="l_sidebar_closer" for="l_sidebar"></label>
    </header>

<main>
    <h1 style="text-align: right">オオカミ君の会計簿</h1>

    <form id="main_form" action="" method="post">
        {% csrf_token %}

        <div class="select_square">
            <select name="category">
                <option value="">カテゴリを選んでください</option>
                {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <input class="text_square" type="text" name="comment" placeholder="主な用途">
        <input class="text_square" type="number" name="income" value="0">
        <input class="text_square" type="number" name="spending" value="0">
        <input class="text_square" id="pay_dt" type="text" name="pay_dt" readonly>
        <input id="main_form_submit" class="button_square" type="button" value="投稿">
    </form>

    <form action="" method="GET">
        <div class="select_square">
            <select name="year">
                {% for year in years %}
                <option value="{{ year }}" {% if selected_year == year %}selected{% endif %}>{{ year }}年</option>
                {% endfor %}
            </select>
        </div>
        <input class="button_square" type="submit" value="絞り込み">
    </form>


    <input id="tab_radio_0" class="tab_radio" type="radio" name="tab_system"  value="0" checked><label class="tab_label" for="tab_radio_0">1年表示</label>
    <input id="tab_radio_1" class="tab_radio" type="radio" name="tab_system"  value="1" ><label class="tab_label" for="tab_radio_1">1月</label>
    <input id="tab_radio_2" class="tab_radio" type="radio" name="tab_system"  value="2" ><label class="tab_label" for="tab_radio_2">2月</label>
    <input id="tab_radio_3" class="tab_radio" type="radio" name="tab_system"  value="3" ><label class="tab_label" for="tab_radio_3">3月</label>
    <input id="tab_radio_4" class="tab_radio" type="radio" name="tab_system"  value="4" ><label class="tab_label" for="tab_radio_4">4月</label>
    <input id="tab_radio_5" class="tab_radio" type="radio" name="tab_system"  value="5" ><label class="tab_label" for="tab_radio_5">5月</label>
    <input id="tab_radio_6" class="tab_radio" type="radio" name="tab_system"  value="6" ><label class="tab_label" for="tab_radio_6">6月</label>
    <input id="tab_radio_7" class="tab_radio" type="radio" name="tab_system"  value="7" ><label class="tab_label" for="tab_radio_7">7月</label>
    <input id="tab_radio_8" class="tab_radio" type="radio" name="tab_system"  value="8" ><label class="tab_label" for="tab_radio_8">8月</label>
    <input id="tab_radio_9" class="tab_radio" type="radio" name="tab_system"  value="9" ><label class="tab_label" for="tab_radio_9">9月</label>
    <input id="tab_radio_10" class="tab_radio" type="radio" name="tab_system" value="10"><label class="tab_label" for="tab_radio_10">10月</label>
    <input id="tab_radio_11" class="tab_radio" type="radio" name="tab_system" value="11"><label class="tab_label" for="tab_radio_11">11月</label>
    <input id="tab_radio_12" class="tab_radio" type="radio" name="tab_system" value="12"><label class="tab_label" for="tab_radio_12">12月</label>

    <div id="tab_area_0" class="tab_area">{% include "asset/table.html" %}</div>
    {% for month in months %}
    <div id="tab_area_{{ forloop.counter }}" class="tab_area">{% include "asset/table.html" with balances=month %}</div>
    {% endfor %}

    <!--モーダルダイアログ-->
      <div id="modal">
        <div id="modal_content">
            <div id="single_graph" class="single_graph">
                <canvas id="graph0"></canvas>
            </div>
            <div id="double_graph" class="double_graph">
                <div class="double_graph_flex">
                    <div class="double_graph_content"><canvas id="graph1"></canvas></div>
                    <div class="double_graph_content"><canvas id="graph2"></canvas></div>
                </div>
            </div>
        </div>
    </div>

    </main>

</body>
</html>

templates/asset/table.html
{% load humanize %}

<div class="pie_chart chart_button"><i class="fas fa-chart-pie"></i></div>
<div class="bar_chart chart_button"><i class="fas fa-chart-bar"></i></div>

<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <td class="text-center">鑑定項目</td>
            <td class="text-center">主な用途</td>
            <td class="text-center">収入金額</td>
            <td class="text-center">支出金額</td>
            <td class="text-center">小計</td>
            <td class="text-center">決算日</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
    {% for balance in balances %}
    <tr>
        <td class="balance_category">{{ balance.category|default:"未分類" }}</td>
        <td class="balance_comment ">{{ balance.comment }}</td>
        <td class="balance_income  ">{{ balance.income|default:"0"|intcomma }}</td>
        <td class="balance_spending">{{ balance.spending|default:"0"|intcomma }}</td>
        <td class="balance_total   ">{{ balance.total|default:"0"|intcomma }}</td>
        <td class="balance_pay_dt  ">{{ balance.pay_dt|date:"Y年m月d日" }}</td>
        <td>
           <form action="{% url 'asset:delete' balance.id %}" method="POST">
               {% csrf_token %}
               <input class="btn btn-outline-dark" type="submit" value="削除">
           </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>